services:
  www:
    depends_on:
      - db
    build: ./docker
    environment:
      WORDPRESS_VERSION: latest
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WP_DEBUG: 1
      WP_DEBUG_LOG: 1
      WPLANG: en
      SMTP_HOST:
      SMTP_PORT:
      SMTP_USER:
      SMTP_PASS:
      SMTP_AUTH:
      SMTP_SSL:
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www
      - ./docker/wp-config.php:/var/www/wp-config.php
      - ./docker/_htaccess:/var/www/.htaccess
      - ./plugins:/var/www/wp-content/plugins
      - ./themes:/var/www/wp-content/themes

  db:
    image: mysql:8.0
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
